name: poetry pytest

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Poetry setup
        uses: ClementWalter/poetry-action@v1
        
      - name: Poetry pytest
        run: poetry run pytest
